### ISSUE TITLE
autocompile on & set target folder

### ISSUE THREAD

**Issue by jllodra** [dstepanov/coffeescript-netbeans#16]
Is is possible to have autocompile on by default? Is it also possible to change target folder for javascript files?

Thanks

**Comment by dstepanov** [comment]
"Is is possible to have autocompile on by default? "

No, but you can select multiple files and turn autocompile on them.

"Is it also possible to change target folder for javascript files?"

No, it would be nice to have somekind of project settings when would you specify things like that otherwise it should be set for every .coffee file.

**Comment by vshjxyz** [comment]
Indeed. the target folder setup would be a killing feature, I'm using symlinks until this will be fixed (hopefully) ;)

**Comment by dstepanov** [comment]
What kind of project do you have? (PHP, Coffeescript, Java,...)
